config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#index"
    get "/home", to: "static_pages#index"
    get "signup", to: "users#new"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "pages/search", to: "pages#search", as: "search_page"
    resources :users, except: %i(destroy index)
    resources :static_pages, only: %i(index show)
    resources :comments, only: %i(create)

    namespace :admin do
      resources :bookings, only: %i(index update)
      resources :locations, except: %i(delete show)
    end

    namespace :user do
      resources :bookings, only: %i(index create update)
      get "seach_yard_for_booking", to: "bookings#seach_yard_for_booking"
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :load_location, only: :show
  def index
    @locations = Location.order_by_name
                         .paginate(page: params[:page],
                            per_page: Settings.paginate.home)
  end

  def show
    yards =  @location.yards.pluck(:id)
    @times = TimeCost.all_time(yards).pluck(:time)
    @comments = @location.comments.newest
    @comment = Comment.new
  end

  private

  def load_location
    @location = Location.find_by(id: params[:id])
    return if @location

    flash[:warning] = t "message.update_booking.not_exist_id"
    redirect_to root_path
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  def val_date
    Date.current.to_formatted_s(:iso8601)
  end
end

app/views/static_pages/_booking.html.erb
<div class="col-sm-2">
  <a href="#" class="btn btn-primary btn-booking" data-toggle="modal" data-target="#exampleModal">Booking</a>
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"><%= t "detail.choose" %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="" class="form-group">
          <label><%= t"detail.date" %></label>
          <input id="datetime" type="date" name="book_date" class="datatime">
          <br>
          <label for="hours"><%= t"detail.time" %></label>

          <select name="hours" id="hours" class="hours">
            <option value="5">5h</option>
            <option value="6">6h</option>
            <option value="7">7h</option>
            <option value="8">8h</option>
          </select>

          <br>
          <label for="type"><%= t"detail.type" %></label>

          <select name="type" id="type" class="type">
            <option value="5">5</option>
            <option value="6">7</option>
            <option value="7">11</option>
          </select>
          <hr>
          <label>San bong ABC</label>
          <div class="row">
            <div class="col-xl-2 yard">
              <a class="btn btn-primary" href="#">1</a>
            </div>
            <div class="col-xl-2 yard">
              <a class="btn btn-primary" href="#">2</a>
            </div>
            <div class="col-xl-2 yard">
              <a class="btn btn-primary" href="#">3</a>
            </div>
            <div class="col-xl-2 yard">
              <a class="btn btn-primary" href="#">4</a>
            </div>
            <div class="col-xl-2 yard">
              <a class="btn btn-primary" href="#">5</a>
            </div>
            <div class="col-xl-2 yard">
              <a class="btn btn-primary" href="#">6</a>
            </div>
            <div class="col-xl-2 yard">
              <a class="btn btn-primary" href="#">7</a>
            </div>
            <div class="col-xl-2 yard">
              <a class="btn btn-primary" href="#">8</a>
            </div>
            <div class="col-xl-2 yard">
              <a class="btn btn-primary" href="#">9</a>
            </div>
          </div>
          <hr>
          <div class="col-xl-12 d-flex justify-content-end">
            <button type="button" class="btn btn-primary mr-3">
              <%= t "booking.name"%>
            </button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">
              <%= t "base.cancel"%>
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/_form_search_for_booking.html.erb
<div class="col-sm-2">
  <%= link_to t("booking.name"), "#", class: "btn btn-primary btn-booking", data: {toggle:"modal", target:"#exampleModal"} %>
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"><%= t "detail.choose" %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_tag user_seach_yard_for_booking_path, method: :get, remote: true do %>
          <label><%= t "detail.date" %></label>
          <%= date_field_tag :date, val_date() %>
          <br>
          <label for="hours"><%= t "detail.time" %></label>
          <%= select_tag :hours, options_for_select(@times) %>
          <br>
          <label for="type"><%= t "detail.type" %></label>
          <%= select_tag :type_yard, raw("<option selected='selected'>5</option><option>7</option><option>11</option>") %>
          <hr>
          <div class="col-xl-12 d-flex justify-content-end">
            <%= button_tag t("booking.search"), type: "submit", class: "btn btn-success" %>
          </div>
          <%= hidden_field_tag :location_id, @location.id %>
        <% end %>
        <div id="result_yards" class="row show-yard-seach">
        </div>
      </div>
    </div>
  </div>
</div>
<%= javascript_pack_tag 'booking', 'data-turbolinks-track': 'reload' %>

app/views/static_pages/_slide.html.erb
<div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <img class="d-block img-fluid" src="/assets/anh01.jpeg" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block img-fluid" src="/assets/anh02.jpeg" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block img-fluid" src="/assets/anh03.jpg" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only"><%= t "home.previous" %></span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only"><%= t "home.next" %></span>
  </a>
</div>

app/views/static_pages/index.html.erb
<% provide(:title, t("home.name")) %>
<% provide(:base_title, t("base.title")) %>
<div class="col-lg-9">
  <%= render "slide" %>
  <div class="row">
    <%= render @locations %>
  </div>
  <%= will_paginate @locations %>
</div>

app/views/static_pages/order.html.erb
<% provide(:title, t("booking.name")) %>
<% provide(:base_title, t("base.title")) %>
<div class="col-lg-9 box-booking">
  <div class="head">
    <h3><%= t "booking.name"%></h3>
  </div>
  <div class="content">
    <table class="table-booking">
      <thead>
        <tr>
          <th scope="col"></th>
          <th scope="col"></th>
          <th scope="col"> <%= t "booking.yard_name" %> </th>
          <th scope="col"> <%= t "booking.yard_code" %> </th>
          <th scope="col"> <%= t "booking.yard_type" %> </th>
          <th scope="col"> <%= t "detail.time" %> </th>
          <th scope="col"> <%= t "detail.date" %> </th>
          <th scope="col"> <%= t "booking.price" %> </th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row">
            <span> <%= t "booking.delete" %> </span>
          </th>
          <td>
            <div class="box-img">
              <img src="" alt="Not img">
            </div>
          </td>
          <td> Yard A </td>
          <td> JAVA </td>
          <td> 5 </td>
          <td> 17:00 </td>
          <td> 10/11/2020 </td>
          <td> 10$ </td>
        </tr>
        <tr>
          <th scope="row">
            <span> <%= t "booking.delete" %> </span>
          </th>
          <td>
            <div class="box-img">
              <img src="" alt="Not img">
            </div>
          </td>
          <td> Yard B</td>
          <td> JAVB </td>
          <td> 5 </td>
          <td> 17:00 </td>
          <td> 10/11/2020 </td>
          <td> 10$ </td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="footer-booking">
    <div class="total">
      <p><b> <%= t "booking.total" %> : </b><span> 20$ </span></p>
    </div>
    <div class="booking">
      <button type="button" class="btn btn-primary mr-3"><%= t "booking.name"%></button>
      <button type="button" class="btn btn-secondary"> <%= t "base.cancel"%> </button>
    </div>
  </div>
</div>

app/views/static_pages/show.html.erb
<% provide(:title, t("detail.name")) %>
<% provide(:base_title, t("base.title")) %>
<div class="col-lg-9">

  <!-- slide-->
  <%= render "slide" %>

  <!-- title yard-->
  <div class="row">
    <h3><%= @location.name %></h3>
  </div>

  <!-- Rating -->
  <div class="row">
    <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
  </div>

  <!-- Button booking -->
  <div class="row justify-content-end mb-4">
    <%= render partial: "form_search_for_booking", object: @times%>
  </div>

  <!-- Address -->
  <div class="row location">
    <p><%= t "home.address"%> <%= @location.address %></p>
    <p><%= t "home.phone"%> <%= @location.phone %></p>
  </div>

  <!-- Description -->
  <div class="row">
    <p class="content-yard">
      <%= @location.description %>
    </p>
  </div>

    <!-- Comment -->
    <%= render "comments/form" %>
    <%= render @comments %>

  </div>
</div>
<%= javascript_pack_tag "reply.js" %>