config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#index"
    get "/home", to: "static_pages#index"
    get "signup", to: "users#new"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "pages/search", to: "pages#search", as: "search_page"
    resources :users, except: %i(destroy index)
    resources :static_pages, only: %i(index show)
    resources :comments, only: %i(create)

    namespace :admin do
      resources :bookings, only: %i(index update)
      resources :locations, except: %i(delete show)
    end

    namespace :user do
      resources :bookings, only: %i(index create update)
      get "seach_yard_for_booking", to: "bookings#seach_yard_for_booking"
    end
  end
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :yards, dependent: :destroy
  has_many :comments, dependent: :destroy

  scope :order_by_name, ->{order :name}

  VALID_PHONE_REGEX = /\A\d[0-9]{9}\z/.freeze
  # validates :name, presence: true,
  #           length: {maximum: Settings.model.default}
  # validates :phone, presence: true,
  #           format: {with: VALID_PHONE_REGEX}
  # validates :address, presence: true,
  #           length: {maximum: Settings.model.default}
  # validates :district, presence: true,
  #           length: {maximum: Settings.model.default}
  scope :search_name, (lambda do |param|
    where("lower(name) LIKE :search", search: "%#{param}%") if param.present?
  end)
end

app/controllers/admin/locations_controller.rb
class Admin::LocationsController < ApplicationController
  before_action :load_location, only: [:update, :edit]

  def index
    @locations = Location.order_by_name
                         .paginate(page: params[:page],
                            per_page: Settings.paginate.manage)
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.new location_params
    if @location.save
      flash[:success] = t "message.add_location"
      redirect_to admin_locations_path
    else
      flash.now[:warning] = t "message.fail"
      render :new
    end
  end

  def edit; end

  def update
    if @location.update location_params
      flash[:success] = t "message.update_location"
      redirect_to admin_locations_path
    else
      flash.now[:warning] = t "message.update_fail"
      render :edit
    end
  end

  private

  def location_params
    params.require(:location)
          .permit(:name, :phone, :address, :district, :description)
  end

  def load_location
    @location = Location.find_by id: params[:id]
    return if @location

    flash[:warning] = t "message.fail"
    redirect_to admin_locations_path
  end
end

app/views/admin/locations/_form.html.erb
<%= form_for([:admin, @location]) do |l| %>
  <%= render "shared/error_messages.html.erb", objects: l.object %>
  <%= l.label :name, t("booking.yard_name") %>
  <%= l.text_field :name, class: "form-control" %>
  <%= l.label :phone, t("home.phone") %>
  <%= l.text_field :phone, class: "form-control" %>
  <%= l.label :address, t("home.address") %>
  <%= l.text_field :address, class: "form-control" %>
  <%= l.label :district, t("district.name") %>
  <%= l.text_field :distric, class: "form-control" %>
  <%= l.label :description, t("home.description") %>
  <%= l.text_field:description, class: "form-control" %>
  <%= l.submit t("home.save"), class: "btn btn-primary" %>
<% end %>

app/views/admin/locations/_location.html.erb
<tr>
  <td> <%= location.name %> </td>
  <td> <%= location.phone %> </td>
  <td> <%= location.address %> </td>
  <td>
    <%= link_to t("detail.name"), "#", class: "btn btn-primary" %>
    <%= link_to t("booking.edit"),edit_admin_location_path(location.id), class: "btn btn-primary" %>
    <%= link_to t("booking.delete"), "#", class: "btn btn-danger" %>
  </td>
</tr>

app/views/admin/locations/edit.html.erb
<% provide(:title, t("booking.new") ) %>
<div class="col-md-9 col-md-offset-3">
<h1> <%= t "booking.new" %> </h1>
  <%= render "form" %>
</div>

app/views/admin/locations/index.html.erb
<% provide(:title, t("detail.name")) %>
<% provide(:base_title, t("base.title")) %>
<div class="col-lg-9">
  <div class="card card-total">
    <div class="card-body">
      <h5 class="card-title">
        <%= link_to t("booking.new"), new_admin_location_path, class: "btn btn-success"%>
      </h5>
    </div>
  </div>
  <table class="table border-bodered table-manager">
    <thead>
      <tr>
        <th scope="col"> <%= t "booking.yard_name" %> </th>
        <th scope="col"> <%= t "home.phone" %> </th>
        <th scope="col"> <%= t "home.address" %> </th>
        <th scope="col"> <%= t "home.option" %> </th>
      </tr>
    </thead>
    <tbody>
      <%= render @locations %>
    </tbody>
  </table>
  <%= will_paginate @locations %>
</div>

app/views/admin/locations/new.html.erb
<% provide(:title, t("booking.new") ) %>
<% provide(:base_title, t("base.title")) %>
<div class="col-md-9 col-md-offset-3">
  <h1> <%= t "booking.new" %> </h1>
    <%= render "form" %>
</div>