config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#index"
    get "/home", to: "static_pages#index"
    get "signup", to: "users#new"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "pages/search", to: "pages#search", as: "search_page"
    resources :users, except: %i(destroy index)
    resources :static_pages, only: %i(index show)
    resources :comments, only: %i(create)

    namespace :admin do
      resources :bookings, only: %i(index update)
      resources :locations, except: %i(delete show)
    end

    namespace :user do
      resources :bookings, only: %i(index create update)
      get "seach_yard_for_booking", to: "bookings#seach_yard_for_booking"
    end
  end
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <%= link_to t("base.name"), home_path, class: "navbar-brand" %>
    <%= render "layouts/search" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <%= link_to t("home.name"), home_path, class: "nav-link" %>
        </li>
        <% if logged_in? %>
           <li class="nav-item">
            <%= link_to t("booking.name"), user_bookings_path,:class => "nav-link" %>
          </li>
          <div class="dropdown show">
            <%= link_to "#", {class: "btn btn-secondary dropdown-toggle", data: {toggle: "dropdown"}} do %>
              <%= t "home.account" %>
              <b class="caret"></b>
            <% end %>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <%= link_to t("home.profile"), current_user, class: "dropdown-item" %>
              <%= link_to t("home.setting"), edit_user_path(current_user), class: "dropdown-item" %>
              <%= link_to t("home.logout"), logout_path,method: :delete, class: "dropdown-item" %>
            </div>
          </div>
          <% else %>
            <li><%= link_to t("home.login"), login_path, class: "nav-link" %></li>
          <% end %>
        </div>
    </div>
</nav>

app/views/layouts/_menu.html.erb
<div class="col-lg-3">
  <% if logged_in? && current_user.admin? %>
    <h1 class="my-4"><%= t "menu_manager.title" %> </h1>
    <div class="list-group">
      <%= link_to t("menu_manager.booking_field"), admin_bookings_path, class:"list-group-item" %>
      <%= link_to t("menu_manager.user"), "#", class:"list-group-item" %>
      <%= link_to t("menu_manager.revenue"), "#", class:"list-group-item" %>
      <%= link_to t("menu_manager.field"), admin_locations_path, class:"list-group-item" %>
    </div>
  <% else %>
  <h1 class="my-4"><%= t "base.location" %></h1>
    <div class="list-group">
      <%= link_to t("district.tk"), "#", class:"list-group-item" %>
      <%= link_to t("district.st"), "#", class:"list-group-item" %>
      <%= link_to t("district.nhs"), "#", class:"list-group-item" %>
      <%= link_to t("district.lc"), "#", class:"list-group-item" %>
      <%= link_to t("district.hc"), "#", class:"list-group-item" %>
      <%= link_to t("district.cl"), "#", class:"list-group-item" %>
      <%= link_to t("district.hv"), "#", class:"list-group-item" %>
      <%= link_to t("district.hs"), "#", class:"list-group-item" %>
    </div>
  <% end %>
</div>

app/views/layouts/_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_search.html.erb
<%= form_tag(search_page_path, method: :GET, class: "navbar-form navbar-left") do %>
  <div class="input-group">
    <%= search_field_tag :search, params[:search], placeholder: t("base.search"), class: "form-control" %>
    <div class="input-group-btn">
      <%= button_tag "", class: "btn btn-info fa fa-search" %>
    </div>
  </div>
<% end %>

app/views/layouts/_title.html.erb
<thead class="thead-dark">
  <tr>
    <th scope="col">
      <%= t "booking.title_admin.image" %>
    </th>
    <th scope="col">
      <%= t "booking.title_admin.name" %>
    </th>
    <th scope="col">
      <%= t "booking.title_admin.type" %>
    </th>
    <th scope="col">
      <%= t "booking.title_admin.time" %>
    </th>
    <th scope="col">
      <%= t "booking.title_admin.code" %>
    </th>
    <th scope="col"></th>
  </tr>
</thead>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | <%= yield(:base_title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>
  <body>
    <%= link_to t("en"), locale: :en %>
    <%= link_to t("vi"), locale: :vi %>
    <%= render "layouts/header" %>
    <div class="container">
      <%= render "layouts/message" %>
      <div class="row">
        <%= render "layouts/menu" %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>